# to reach rules detail, please open `http://eslint.org/docs/rules/:rule_name`

extends: 'airbnb'

rules:
  ###### Common style

  ## remove your un-used vars
  no-unused-vars: 1

  ## allow function hoisting
  no-use-before-define: [2, "nofunc"]

  ## no reassign
  no-param-reassign: 2

  ## allow single line if condition like `if (foo) foo++`
  curly: [2, "multi-line"]

  ## error if you are not follow 2 spaces as indent
  indent: [2, 2, {"SwitchCase": 1}]

  ## use single quotes, not double single.
  quotes: [2, "single"]

  ## use const or let to instead var
  no-var: 2

  ## no comma style, ref ASI
  # allow you written `;[].forEach.apply` but not allow `jQuery('body').remove();`
  semi: [2, "never"]

  semi-spacing:
    - 2
    - before: false
      after: true

  ## allow you make [1, 2, 3,] or [a:1, b:1, c:1,] to written in multiline.
  comma-dangle: 0

  ## don't care let or const, when your vars are never modified
  prefer-const: 0
